package bepler.lrpage.code.generator;

import java.io.File;
import java.io.IOException;

import bepler.lrpage.grammar.Grammar;
import bepler.lrpage.parser.Symbols;

import com.sun.codemodel.JClassAlreadyExistsException;
import com.sun.codemodel.JCodeModel;
import com.sun.codemodel.JDefinedClass;
import com.sun.codemodel.JDocComment;

public class CodeGenerator {
	
	private static final String CLASS_HEADER_DOC = "This class was generated by LRPaGe using the com.sun.codemodel library. "
			+ "LRPaGe is availbe from https://github.com/tbepler/LRPaGe. CodeModel is available from https://codemodel.java.net/.";
	
	private static final String EOF = "EOF";
	
	private final JCodeModel model = new JCodeModel();
	private final NodeGenerator nodeGen;
	private final LexerGenerator lexerGen;
	private final ParserGenerator parserGen;
	
	public CodeGenerator(String pckg, Grammar g){
		try {
			Symbols symbols = new Symbols(g, EOF);
			nodeGen = new NodeGenerator(symbols, pckg, model);
			lexerGen = new LexerGenerator(pckg, model, nodeGen);
			lexerGen.generate(g.getTokens());
			parserGen = new ParserGenerator(symbols);
			JDefinedClass parser = parserGen.generate(pckg, model,
					lexerGen.getLexerClass(), nodeGen);
			
			JDefinedClass printVisitor = MainGenerator.generatePrintVisitor(
					pckg, model, nodeGen.getVisitorInterface(),
					nodeGen.getTokenNodeClasses());
			MainGenerator.generateMain(pckg, model, lexerGen.getLexerClass(),
					parser, printVisitor,nodeGen.getNodeInterface());
			
		} catch (JClassAlreadyExistsException e) {
			throw new RuntimeException(e);
		}
	}
	
	public void write(File dir) throws IOException{
		model.build(dir);
	}
	
	public static void appendJDocHeader(JDefinedClass clazz){
		JDocComment doc = clazz.javadoc();
		doc.append(CLASS_HEADER_DOC);
	}

}
