
package bepler.lrpage.ebnf.parser.nodes;

import bepler.lrpage.ebnf.parser.Visitor;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public class BothDirective
    extends DirectiveAbstractNode
{

    public final AssocAbstractNode assoc0;
    public final IntToken int1;
    public final SymbolListAbstractNode symbollist2;

    public BothDirective(AssocAbstractNode assoc0, IntToken int1, SymbolListAbstractNode symbollist2, TerminationToken termination3) {
        this.assoc0 = assoc0;
        this.int1 = int1;
        this.symbollist2 = symbollist2;
    }

    @Override
    public int getLine() {
        return assoc0 .getLine();
    }

    @Override
    public int getPos() {
        return assoc0 .getPos();
    }

    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }

}
