
package bepler.lrpage.ebnf.parser.nodes;

import bepler.lrpage.ebnf.parser.Visitor;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public class ConcatRHS
    extends RHSAbstractNode
{

    public final RHSAbstractNode rhs0;
    public final RHSAbstractNode rhs1;

    public ConcatRHS(RHSAbstractNode rhs0, ConcatenationToken concatenation1, RHSAbstractNode rhs2) {
        this.rhs0 = rhs0;
        this.rhs1 = rhs2;
    }

    @Override
    public int getLine() {
        return rhs0 .getLine();
    }

    @Override
    public int getPos() {
        return rhs0 .getPos();
    }

    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = ((hash* 13)+ rhs0 .hashCode());
        hash = ((hash* 13)+ rhs1 .hashCode());
        hash = ((hash* 13)+ getClass().hashCode());
        return hash;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (null == o) {
            return false;
        }
        if (!(o instanceof ConcatRHS)) {
            return false;
        }
        ConcatRHS castResult = ((ConcatRHS) o);
        if (!this.rhs0 .equals(castResult.rhs0)) {
            return false;
        }
        if (!this.rhs1 .equals(castResult.rhs1)) {
            return false;
        }
        return true;
    }

}
