
package bepler.lrpage.ebnf.parser.nodes;

import bepler.lrpage.ebnf.parser.Visitor;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public class GrammarStartBlock
    extends GrammarAbstractNode
{

    public final BlockAbstractNode block0;

    public GrammarStartBlock(BlockAbstractNode block0) {
        this.block0 = block0;
    }

    @Override
    public int getLine() {
        return block0 .getLine();
    }

    @Override
    public int getPos() {
        return block0 .getPos();
    }

    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = (hash*(13 + block0 .hashCode()));
        return hash;
    }

    @Override
    public boolean equals(Object o) {
        if (this.equals(o)) {
            return true;
        }
        if (o.equals(null)) {
            return false;
        }
        if (!(o instanceof GrammarStartBlock)) {
            return false;
        }
        GrammarStartBlock castResult = ((GrammarStartBlock) o);
        if (!this.block0 .equals(castResult.block0)) {
            return false;
        }
        return true;
    }

}
