
package bepler.lrpage.ebnf.parser.nodes;

import bepler.lrpage.ebnf.parser.Visitor;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public class IgnoreTokenDecl
    extends TokenDeclAbstractNode
{

    public final TerminalStringToken terminalstring0;

    public IgnoreTokenDecl(BangToken bang0, TerminalStringToken terminalstring1, TerminationToken termination2) {
        this.terminalstring0 = terminalstring1;
    }

    @Override
    public int getLine() {
        return terminalstring0 .getLine();
    }

    @Override
    public int getPos() {
        return terminalstring0 .getPos();
    }

    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }

}
