
package bepler.lrpage.ebnf.parser.nodes;

import bepler.lrpage.ebnf.parser.Visitor;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public class PrecRHS
    extends RHSAbstractNode
{

    public final RHSAbstractNode rhs0;
    public final PrecDeclAbstractNode precdecl1;

    public PrecRHS(RHSAbstractNode rhs0, PrecDeclAbstractNode precdecl1) {
        this.rhs0 = rhs0;
        this.precdecl1 = precdecl1;
    }

    @Override
    public int getLine() {
        return rhs0 .getLine();
    }

    @Override
    public int getPos() {
        return rhs0 .getPos();
    }

    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }

}
