
package bepler.lrpage.ebnf.parser.nodes;

import bepler.lrpage.ebnf.parser.Visitor;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public class PrecDirectiveBlock
    extends BlockAbstractNode
{

    public final DirectiveListAbstractNode directivelist0;

    public PrecDirectiveBlock(SpecialToken special0, PrecedenceKeywordToken precedencekeyword1, StartBlockToken startblock2, DirectiveListAbstractNode directivelist3) {
        this.directivelist0 = directivelist3;
    }

    @Override
    public int getLine() {
        return directivelist0 .getLine();
    }

    @Override
    public int getPos() {
        return directivelist0 .getPos();
    }

    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = ((hash* 13)+ directivelist0 .hashCode());
        hash = ((hash* 13)+ getClass().hashCode());
        return hash;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (null == o) {
            return false;
        }
        if (!(o instanceof PrecDirectiveBlock)) {
            return false;
        }
        PrecDirectiveBlock castResult = ((PrecDirectiveBlock) o);
        if (!this.directivelist0 .equals(castResult.directivelist0)) {
            return false;
        }
        return true;
    }

}
