
package bepler.lrpage.ebnf.parser.nodes;

import bepler.lrpage.ebnf.parser.Visitor;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public class PriorityDirective
    extends DirectiveAbstractNode
{

    public final IntToken int0;
    public final SymbolListAbstractNode symbollist1;

    public PriorityDirective(IntToken int0, SymbolListAbstractNode symbollist1, TerminationToken termination2) {
        this.int0 = int0;
        this.symbollist1 = symbollist1;
    }

    @Override
    public int getLine() {
        return int0 .getLine();
    }

    @Override
    public int getPos() {
        return int0 .getPos();
    }

    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }

}
