
package bepler.lrpage.ebnf.parser.nodes;

import bepler.lrpage.ebnf.parser.Visitor;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public class PseudoDeclList
    extends PseudoDeclListAbstractNode
{

    public final PseudoDeclListAbstractNode pseudodecllist0;
    public final PseudoDeclAbstractNode pseudodecl1;

    public PseudoDeclList(PseudoDeclListAbstractNode pseudodecllist0, PseudoDeclAbstractNode pseudodecl1) {
        this.pseudodecllist0 = pseudodecllist0;
        this.pseudodecl1 = pseudodecl1;
    }

    @Override
    public int getLine() {
        return pseudodecllist0 .getLine();
    }

    @Override
    public int getPos() {
        return pseudodecllist0 .getPos();
    }

    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = (hash*(13 + pseudodecllist0 .hashCode()));
        hash = (hash*(13 + pseudodecl1 .hashCode()));
        return hash;
    }

    @Override
    public boolean equals(Object o) {
        if (this.equals(o)) {
            return true;
        }
        if (o.equals(null)) {
            return false;
        }
        if (!(o instanceof PseudoDeclList)) {
            return false;
        }
        PseudoDeclList castResult = ((PseudoDeclList) o);
        if (!this.pseudodecllist0 .equals(castResult.pseudodecllist0)) {
            return false;
        }
        if (!this.pseudodecl1 .equals(castResult.pseudodecl1)) {
            return false;
        }
        return true;
    }

}
