
package bepler.lrpage.ebnf.parser.nodes;

import bepler.lrpage.ebnf.parser.Visitor;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public class PseudoDeclBlock
    extends BlockAbstractNode
{

    public final PseudoDeclListAbstractNode pseudodecllist0;

    public PseudoDeclBlock(SpecialToken special0, PseudonymKeywordToken pseudonymkeyword1, StartBlockToken startblock2, PseudoDeclListAbstractNode pseudodecllist3) {
        this.pseudodecllist0 = pseudodecllist3;
    }

    @Override
    public int getLine() {
        return pseudodecllist0 .getLine();
    }

    @Override
    public int getPos() {
        return pseudodecllist0 .getPos();
    }

    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = ((hash* 13)+ pseudodecllist0 .hashCode());
        hash = ((hash* 13)+ getClass().hashCode());
        return hash;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (null == o) {
            return false;
        }
        if (!(o instanceof PseudoDeclBlock)) {
            return false;
        }
        PseudoDeclBlock castResult = ((PseudoDeclBlock) o);
        if (!this.pseudodecllist0 .equals(castResult.pseudodecllist0)) {
            return false;
        }
        return true;
    }

}
