
package bepler.lrpage.ebnf.parser.nodes;

import bepler.lrpage.ebnf.parser.Visitor;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public class PseudonymDecl
    extends PseudoDeclAbstractNode
{

    public final SymbolAbstractNode symbol0;
    public final TerminalStringToken terminalstring1;

    public PseudonymDecl(SymbolAbstractNode symbol0, DefinitionToken definition1, TerminalStringToken terminalstring2, TerminationToken termination3) {
        this.symbol0 = symbol0;
        this.terminalstring1 = terminalstring2;
    }

    @Override
    public int getLine() {
        return symbol0 .getLine();
    }

    @Override
    public int getPos() {
        return symbol0 .getPos();
    }

    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = ((hash* 13)+ symbol0 .hashCode());
        hash = ((hash* 13)+ terminalstring1 .hashCode());
        hash = ((hash* 13)+ getClass().hashCode());
        return hash;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (null == o) {
            return false;
        }
        if (!(o instanceof PseudonymDecl)) {
            return false;
        }
        PseudonymDecl castResult = ((PseudonymDecl) o);
        if (!this.symbol0 .equals(castResult.symbol0)) {
            return false;
        }
        if (!this.terminalstring1 .equals(castResult.terminalstring1)) {
            return false;
        }
        return true;
    }

}
