
package bepler.lrpage.ebnf.parser.nodes;

import bepler.lrpage.ebnf.parser.Visitor;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public class RuleDeclList
    extends RuleDeclListAbstractNode
{

    public final RuleDeclListAbstractNode ruledecllist0;
    public final RuleDeclAbstractNode ruledecl1;

    public RuleDeclList(RuleDeclListAbstractNode ruledecllist0, RuleDeclAbstractNode ruledecl1) {
        this.ruledecllist0 = ruledecllist0;
        this.ruledecl1 = ruledecl1;
    }

    @Override
    public int getLine() {
        return ruledecllist0 .getLine();
    }

    @Override
    public int getPos() {
        return ruledecllist0 .getPos();
    }

    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = ((hash* 13)+ ruledecllist0 .hashCode());
        hash = ((hash* 13)+ ruledecl1 .hashCode());
        hash = ((hash* 13)+ getClass().hashCode());
        return hash;
    }

    @Override
    public boolean equals(Object o) {
        if (this.equals(o)) {
            return true;
        }
        if (o.equals(null)) {
            return false;
        }
        if (!(o instanceof RuleDeclList)) {
            return false;
        }
        RuleDeclList castResult = ((RuleDeclList) o);
        if (!this.ruledecllist0 .equals(castResult.ruledecllist0)) {
            return false;
        }
        if (!this.ruledecl1 .equals(castResult.ruledecl1)) {
            return false;
        }
        return true;
    }

}
