
package bepler.lrpage.ebnf.parser.nodes;

import bepler.lrpage.ebnf.parser.Visitor;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public class RuleDeclList
    extends RuleDeclListAbstractNode
{

    public final RuleDeclListAbstractNode ruledecllist0;
    public final RuleDeclAbstractNode ruledecl1;

    public RuleDeclList(RuleDeclListAbstractNode ruledecllist0, RuleDeclAbstractNode ruledecl1) {
        this.ruledecllist0 = ruledecllist0;
        this.ruledecl1 = ruledecl1;
    }

    @Override
    public int getLine() {
        return ruledecllist0 .getLine();
    }

    @Override
    public int getPos() {
        return ruledecllist0 .getPos();
    }

    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }

}
