
package bepler.lrpage.ebnf.parser.nodes;

import bepler.lrpage.ebnf.parser.Visitor;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public class RuleDecl
    extends RuleDeclAbstractNode
{

    public final IdentifierToken identifier0;
    public final RHSAbstractNode rhs1;

    public RuleDecl(IdentifierToken identifier0, DefinitionToken definition1, RHSAbstractNode rhs2, TerminationToken termination3) {
        this.identifier0 = identifier0;
        this.rhs1 = rhs2;
    }

    @Override
    public int getLine() {
        return identifier0 .getLine();
    }

    @Override
    public int getPos() {
        return identifier0 .getPos();
    }

    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = ((hash* 13)+ identifier0 .hashCode());
        hash = ((hash* 13)+ rhs1 .hashCode());
        hash = ((hash* 13)+ getClass().hashCode());
        return hash;
    }

    @Override
    public boolean equals(Object o) {
        if (this.equals(o)) {
            return true;
        }
        if (o.equals(null)) {
            return false;
        }
        if (!(o instanceof RuleDecl)) {
            return false;
        }
        RuleDecl castResult = ((RuleDecl) o);
        if (!this.identifier0 .equals(castResult.identifier0)) {
            return false;
        }
        if (!this.rhs1 .equals(castResult.rhs1)) {
            return false;
        }
        return true;
    }

}
