
package bepler.lrpage.ebnf.parser.nodes;

import bepler.lrpage.ebnf.parser.Visitor;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public class RuleDeclListHead
    extends RuleDeclListAbstractNode
{

    public final RuleDeclAbstractNode ruledecl0;

    public RuleDeclListHead(RuleDeclAbstractNode ruledecl0) {
        this.ruledecl0 = ruledecl0;
    }

    @Override
    public int getLine() {
        return ruledecl0 .getLine();
    }

    @Override
    public int getPos() {
        return ruledecl0 .getPos();
    }

    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }

}
