
package bepler.lrpage.ebnf.parser.nodes;

import bepler.lrpage.ebnf.parser.Visitor;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public class SymbolListHead
    extends SymbolListAbstractNode
{

    public final SymbolAbstractNode symbol0;

    public SymbolListHead(SymbolAbstractNode symbol0) {
        this.symbol0 = symbol0;
    }

    @Override
    public int getLine() {
        return symbol0 .getLine();
    }

    @Override
    public int getPos() {
        return symbol0 .getPos();
    }

    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }

}
