
package bepler.lrpage.ebnf.parser.nodes;

import bepler.lrpage.ebnf.parser.Visitor;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public class SymbolList
    extends SymbolListAbstractNode
{

    public final SymbolListAbstractNode symbollist0;
    public final SymbolAbstractNode symbol1;

    public SymbolList(SymbolListAbstractNode symbollist0, ConcatenationToken concatenation1, SymbolAbstractNode symbol2) {
        this.symbollist0 = symbollist0;
        this.symbol1 = symbol2;
    }

    @Override
    public int getLine() {
        return symbollist0 .getLine();
    }

    @Override
    public int getPos() {
        return symbollist0 .getPos();
    }

    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = (hash*(13 + symbollist0 .hashCode()));
        hash = (hash*(13 + symbol1 .hashCode()));
        return hash;
    }

    @Override
    public boolean equals(Object o) {
        if (this.equals(o)) {
            return true;
        }
        if (o.equals(null)) {
            return false;
        }
        if (!(o instanceof SymbolList)) {
            return false;
        }
        SymbolList castResult = ((SymbolList) o);
        if (!this.symbollist0 .equals(castResult.symbollist0)) {
            return false;
        }
        if (!this.symbol1 .equals(castResult.symbol1)) {
            return false;
        }
        return true;
    }

}
