
package bepler.lrpage.ebnf.parser.nodes;

import bepler.lrpage.ebnf.parser.Visitor;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public class SymbolList
    extends SymbolListAbstractNode
{

    public final SymbolListAbstractNode symbollist0;
    public final SymbolAbstractNode symbol1;

    public SymbolList(SymbolListAbstractNode symbollist0, ConcatenationToken concatenation1, SymbolAbstractNode symbol2) {
        this.symbollist0 = symbollist0;
        this.symbol1 = symbol2;
    }

    @Override
    public int getLine() {
        return symbollist0 .getLine();
    }

    @Override
    public int getPos() {
        return symbollist0 .getPos();
    }

    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }

}
