
package bepler.lrpage.ebnf.parser.nodes;

import bepler.lrpage.ebnf.parser.Visitor;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public class TokenDeclBlock
    extends BlockAbstractNode
{

    public final TokenDeclListAbstractNode tokendecllist0;

    public TokenDeclBlock(SpecialToken special0, TokensKeywordToken tokenskeyword1, StartBlockToken startblock2, TokenDeclListAbstractNode tokendecllist3) {
        this.tokendecllist0 = tokendecllist3;
    }

    @Override
    public int getLine() {
        return tokendecllist0 .getLine();
    }

    @Override
    public int getPos() {
        return tokendecllist0 .getPos();
    }

    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = (hash*(13 + tokendecllist0 .hashCode()));
        return hash;
    }

    @Override
    public boolean equals(Object o) {
        if (this.equals(o)) {
            return true;
        }
        if (o.equals(null)) {
            return false;
        }
        if (!(o instanceof TokenDeclBlock)) {
            return false;
        }
        TokenDeclBlock castResult = ((TokenDeclBlock) o);
        if (!this.tokendecllist0 .equals(castResult.tokendecllist0)) {
            return false;
        }
        return true;
    }

}
