
package bepler.lrpage.ebnf.parser.nodes;

import bepler.lrpage.ebnf.parser.Visitor;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public class TokenDeclList
    extends TokenDeclListAbstractNode
{

    public final TokenDeclListAbstractNode tokendecllist0;
    public final TokenDeclAbstractNode tokendecl1;

    public TokenDeclList(TokenDeclListAbstractNode tokendecllist0, TokenDeclAbstractNode tokendecl1) {
        this.tokendecllist0 = tokendecllist0;
        this.tokendecl1 = tokendecl1;
    }

    @Override
    public int getLine() {
        return tokendecllist0 .getLine();
    }

    @Override
    public int getPos() {
        return tokendecllist0 .getPos();
    }

    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }

}
