
package bepler.lrpage.ebnf.parser.nodes;

import bepler.lrpage.ebnf.parser.Visitor;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public class TokenDeclList
    extends TokenDeclListAbstractNode
{

    public final TokenDeclListAbstractNode tokendecllist0;
    public final TokenDeclAbstractNode tokendecl1;

    public TokenDeclList(TokenDeclListAbstractNode tokendecllist0, TokenDeclAbstractNode tokendecl1) {
        this.tokendecllist0 = tokendecllist0;
        this.tokendecl1 = tokendecl1;
    }

    @Override
    public int getLine() {
        return tokendecllist0 .getLine();
    }

    @Override
    public int getPos() {
        return tokendecllist0 .getPos();
    }

    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = ((hash* 13)+ tokendecllist0 .hashCode());
        hash = ((hash* 13)+ tokendecl1 .hashCode());
        hash = ((hash* 13)+ getClass().hashCode());
        return hash;
    }

    @Override
    public boolean equals(Object o) {
        if (this.equals(o)) {
            return true;
        }
        if (o.equals(null)) {
            return false;
        }
        if (!(o instanceof TokenDeclList)) {
            return false;
        }
        TokenDeclList castResult = ((TokenDeclList) o);
        if (!this.tokendecllist0 .equals(castResult.tokendecllist0)) {
            return false;
        }
        if (!this.tokendecl1 .equals(castResult.tokendecl1)) {
            return false;
        }
        return true;
    }

}
