
package bepler.lrpage.ebnf.parser.nodes;

import bepler.lrpage.ebnf.parser.Visitor;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public class TokenDeclBlock
    extends BlockAbstractNode
{

    public final TokenDeclListAbstractNode tokendecllist0;

    public TokenDeclBlock(SpecialToken special0, TokensKeywordToken tokenskeyword1, StartBlockToken startblock2, TokenDeclListAbstractNode tokendecllist3) {
        this.tokendecllist0 = tokendecllist3;
    }

    @Override
    public int getLine() {
        return tokendecllist0 .getLine();
    }

    @Override
    public int getPos() {
        return tokendecllist0 .getPos();
    }

    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }

}
