
package bepler.lrpage.ebnf.parser;

import bepler.lrpage.ebnf.parser.nodes.AltRHS;
import bepler.lrpage.ebnf.parser.nodes.ConcatRHS;
import bepler.lrpage.ebnf.parser.nodes.EmptySymbol;
import bepler.lrpage.ebnf.parser.nodes.ErrorToken;
import bepler.lrpage.ebnf.parser.nodes.GrammarAppendBlock;
import bepler.lrpage.ebnf.parser.nodes.GrammarStartBlock;
import bepler.lrpage.ebnf.parser.nodes.IdSymbol;
import bepler.lrpage.ebnf.parser.nodes.IdentifierToken;
import bepler.lrpage.ebnf.parser.nodes.IgnoreTokenDecl;
import bepler.lrpage.ebnf.parser.nodes.LitSymbol;
import bepler.lrpage.ebnf.parser.nodes.RuleDecl;
import bepler.lrpage.ebnf.parser.nodes.RuleDeclBlock;
import bepler.lrpage.ebnf.parser.nodes.RuleDeclList;
import bepler.lrpage.ebnf.parser.nodes.RuleDeclListHead;
import bepler.lrpage.ebnf.parser.nodes.SymbolRHS;
import bepler.lrpage.ebnf.parser.nodes.TerminalStringToken;
import bepler.lrpage.ebnf.parser.nodes.TokenDecl;
import bepler.lrpage.ebnf.parser.nodes.TokenDeclBlock;
import bepler.lrpage.ebnf.parser.nodes.TokenDeclList;
import bepler.lrpage.ebnf.parser.nodes.TokenDeclListHead;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public interface Visitor {


    public void visit(IdentifierToken node);

    public void visit(TerminalStringToken node);

    public void visit(ErrorToken node);

    public void visit(GrammarStartBlock node);

    public void visit(GrammarAppendBlock node);

    public void visit(TokenDeclBlock node);

    public void visit(RuleDeclBlock node);

    public void visit(TokenDeclListHead node);

    public void visit(TokenDeclList node);

    public void visit(RuleDeclListHead node);

    public void visit(RuleDeclList node);

    public void visit(TokenDecl node);

    public void visit(IgnoreTokenDecl node);

    public void visit(RuleDecl node);

    public void visit(SymbolRHS node);

    public void visit(AltRHS node);

    public void visit(ConcatRHS node);

    public void visit(EmptySymbol node);

    public void visit(IdSymbol node);

    public void visit(LitSymbol node);

}
